# fly.toml app configuration file generated for datingappvn on 2024-07-14T08:59:24+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingappvn'
primary_region = 'sin'

[build]
  image = 'hung057/datingapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dmftnjvdv"
  CloudinarySettings__ApiKey="779466428238276"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
